### ISSUE TITLE
shipit 1.5.1 breaks shipit-db

### ISSUE THREAD

**Issue by diggy** [timkelty/shipit-db#17]
Hi @timkelty,

It looks like `shipit` 1.5.1 breaks `shipit-db`, could you take a look? The `shipit.db.options` in the Gruntfile are ignored, causing the local env to be undefined, and `bunzip2` being used instead of `bzip2`.

Thanks!

**Comment by diggy** [comment]
temp fix: specifying the `shipit-cli` version in package.json: `"shipit-cli": "1.4.1"`

**Comment by timkelty** [comment]
@diggy can you post your config?

**Comment by timkelty** [comment]
1.5.1 changed how `default` is merged into your environments.

Specifically, it uses `_.assign`, instead of `_.merge`, for more expected results with merging, and to match how the merging is documented: https://github.com/shipitjs/shipit#customising-environments

This was perceived us as a "fix", hence the non-major version change, but that may have been a bit presumptuous.

I suspect your problem lies there, but if you post your config we can figure it out.

**Comment by diggy** [comment]
@timkelty tnx for looking into this! you can find a relevant portion of our config here: https://gist.github.com/diggy/32fb76a0e786edfc02cd6321fd1e225c

**Comment by timkelty** [comment]
Yep! So unfortunately this type of setup wont work anymore.
Sorry I should have accounted for people relying on this and released a major version.

So, when merging - since environments fully overwrite any keys present in the defaults, if you want to inherit those defaults, you'll want to do something like: https://gist.github.com/timkelty/9500ae58bb3c2765a403e2daffa83036

If you're curious - the reasoning for the change is here: https://github.com/shipitjs/shipit/issues/137
How it works now was always the intention, but I'm sorry - this should have been released as a breaking change.

**Comment by timkelty** [comment]
@diggy ok, I published a patch that reverted the change: `1.5.2`, so if you reinstall (to `^1.5.0`) or whatever, it should continue to work for you. 

The breaking change is now released as `2.0.0`.

**Comment by diggy** [comment]
@timkelty tnx, will check asap, but looks good already!
